import { EntryPage } from '@/components/entry-page/entry-page';
import { JoinRoomForm } from '@/components/forms/rooms/join-room-form';

const joinRoomHeadings = [
  'Ready to turn up?',
  "What's your vibe?",
  'The aux is yours!',
  'Ready to make some noise?',
  'Your song awaits.',
  'Take the aux.',
  "Let's get loud!",
  'Get in the mix.',
  'What should we play?',
  'Got a banger?',
  'The party starts here.',
  'Give us something good.',
  'Turn it up!',
  "Let's do this thing.",
  'What are we playing?',
  'Got a song in mind?',
  'What should we play?',
  'Your turn on the aux.',
  'Give the DJ something to work with.',
  "Show us what you've got.",
  'Got a banger?',
  'You just got handed the aux.',
  "Who's ready?",
  "Let's get it started!",
  'What are we feeling?',
  'Time to vibe!',
  "Let's set it off!",
  'You know what time it is!',
  "It's about to get loud!",
  "Let's make tonight count!",
  'Bring your best song!',
  "Don't be shy!",
  'You came to party!',
  "Let's make some memories!",
  'The night is young!',
  'This is your sign!',
  'You know the vibes!',
  "Let's get into it!",
  "Now we're talking!",
  "Let's keep it moving!",
  'Turn the speakers up!',
  'Crank it up!',
  'Let the music play!',
  "We're just getting started!",
  'The vibes are calling!',
  'Something good is playing!',
  "What's the move?",
  'What are you feeling?',
  "What's the next move?",
  "Who's picking the next one?",
  'What should we hear?',
  "What's your pick?",
  'Got something in mind?',
  'Feeling something?',
  'Know a good one?',
  'Have a song for us?',
  "What's the anthem?",
  "What's the move tonight?",
  "Where's the energy?",
  'Can you feel it?',
  'Feeling the vibe?',
  'Ready for the next one?',
  'Should we turn it up?',
  'One for the playlist?',
  'What comes next?',
  'Who brought the aux?',
  'Who picked this one?',
  "Who's up next?",
  'Your turn!',
  'Make it count!',
  "Don't hold back!",
  'Send it!',
  "Let's hear it!",
  'Hit us with one!',
  'Drop something good!',
  'Throw one in!',
  'Put us on!',
  'Give us a good one!',
  "Let's see what you've got!",
  'Show us your taste!',
  'Bring the heat!',
  'Keep that energy!',
  'Keep it going!',
  "Don't let the music stop!",
  "We're not done yet!",
  "There's always room for one more!",
  'Another one!',
  'Run it back!',
  'Play that one!',
  "That's the one!",
  "This one's yours!",
  'Make your pick!',
  'Pick your poison!',
  'Choose wisely!',
  'Trust your taste!',
  'You know what to do!',
  "Let's make it interesting!",
  'Things are heating up!',
  "We're getting started!",
  'The floor is yours!',
  'Take us somewhere!',
  'Set the tone!',
  'Set the mood!',
  'Bring your energy!',
  'Bring your flavor!',
  "Let's change the vibe!",
  "Let's shake things up!",
  "Let's switch it up!",
  'Keep the vibes alive!',
  'The vibe starts here!',
  'Good times ahead!',
  "Something's gotta play!",
  "Let's find the next one!",
  "Let's find a good one!",
  "What'll it be?",
  "What's it gonna be?",
  'You feeling lucky?',
  'Ready when you are!',
];


const heading = joinRoomHeadings[Math.floor(Math.random() * joinRoomHeadings.length)];

export default function JoinRoom() {
  return (
    <EntryPage artwork="dj">
      <div className="mb-8 flex flex-col items-center gap-2 text-center">
        <h1 className="text-xl font-bold text-white tracking-tight">{heading}</h1>
        <p className="text-xs text-white/50">
          Enter the room code shared by your host to start requesting music.
        </p>
      </div>
      <JoinRoomForm />
    </EntryPage>
  );
}
